import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-full bg-gradient-to-r from-[#052149] via-[#1f114e] to-[#040925]">
          <Navbar/>
        {children}
        </div>
        </body>
    </html>
  );
}
